### ISSUE TITLE
[Suggestion]: Client Sided?

### ISSUE THREAD

**Issue by Pendragone95** [Komaru-cats/Vanilla_Fireflies#1]
### Describe your suggestion

Make the fireflies effect client sided if its not a bug. It only works in singleplayer

### Before creating a new suggestion

- [X] I made sure that this function is not available at the moment in Vanilla Fireflies

**Comment by ItzSkyReed** [comment]
If you downloaded a mod, then this is in any case a datapack and it will only work where it is installed, be it a server or a single-player game.  The mod version differs only in that the datapack is automatically installed in every world you enter.  I haven't planned to make a real mod for this yet, but maybe it will be in the future.  I hope I answered your question clearly.

**Comment by Evlyman** [comment]
> Если вы скачали мод, то это в любом случае датапак и он будет работать только там, где он установлен, будь то сервер или однопользовательская игра. Версия мода отличается только тем, что датапак автоматически устанавливается в каждом мире, в который вы входите. Я пока не планировал делать настоящий мод для этого, но, возможно, это будет в будущем. Надеюсь, я ясно ответил на ваш вопрос.

Heyy i'll be at the front of the line when you do. I really want to find a mod for particle minimalism. Such as fireflies and the like, but I can't find one, how sad
