### ISSUE TITLE
[Suggestion]:  Would love to have more firefly

### ISSUE THREAD

**Issue by Sushikee** [Komaru-cats/Vanilla_Fireflies#2]
### Describe your suggestion

I know that you already have 3 preset for the amount of particle but it would be nice to have a lot more

### Before creating a new suggestion

- [X] I made sure that this function is not available at the moment in Vanilla Fireflies

**Comment by ItzSkyReed** [comment]
I think I'll figure something out.

**Comment by Sushikee** [comment]
Hey, sorry for asking but it would be nice if the firefly have its own texture file. Because, I like the old texture of firefly which only consist of 2 pixel.

**Comment by ItzSkyReed** [comment]
> Hey, sorry for asking but it would be nice if the firefly have its own texture file. Because, I like the old texture of firefly which only consist of 2 pixel.

Sorry, but I haven't got any plans to do it because I can't add new particles. If you really want you can change texture of `ominous_spawning` particle

**Comment by ItzSkyReed** [comment]
Done in [85dd989](https://github.com/Komaru-cats/Vanilla_Fireflies/commit/85dd98908d9e6cac7b189a8459af1d6168718867)
